# Generated by Django 6.0.4 on 2026-04-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('fase_torneo', models.CharField(choices=[('FG', 'Fase de Grupo'), ('16', 'Dieciseisavos'), ('8', 'Octavos'), ('4', 'Cuartos'), ('SF', 'Semifinal'), ('F', 'Final')], max_length=2)),
                ('seleccion_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='mundial.seleccion')),
                ('seleccion_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='mundial.seleccion')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('posicion', models.CharField(choices=[('AR', 'Arquero'), ('DF', 'Defensor'), ('MC', 'Mediocampista'), ('DL', 'Delantero')], max_length=2)),
                ('edad', models.IntegerField()),
                ('goles', models.IntegerField(default=0)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial.seleccion')),
            ],
        ),
    ]
