# Generated by Django 6.0.4 on 2026-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_alter_jugador_edad_alter_jugador_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.CharField(default='Estadio', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_partido',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estadios'),
        ),
    ]
